name: CI / Deploy backend -> Render (curl)

# trigger on pushes to your 'backend' branch
on:
    push:
        branches: ["backend"]
    workflow_dispatch:

jobs:
    ci:
        name: Run CI
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Check for backend/package.json
              id: check_pkg
              run: |
                if [ -f backend/package.json ]; then
                    echo "exists=true" >> $GITHUB_OUTPUT
                else 
                    echo "exists=false" >> $GITHUB_OUTPUT
                fi

            - name: Set up Node
              if: steps.check_pkg.outputs.exists == 'true'
              uses: actions/setup-node@v4
              with:
                node-version: '22.19.0'

            - name: Install dependencies & run tests
              if: steps.check_pkg.outputs.exists == 'true'
              run: |
                cd backend
                npm install
                if grep -q "\"test\":" package.json; then
                    npm test -- --passWithNoTests
                else
                    echo "No test script found - skipping tests."
                fi
              env:
                CI: true

    deploy:
        name: Deploy to render
        runs-on: ubuntu-latest
        needs: ci
        steps:
            - name: Checkout repo (for context/logs)
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: Verify Render secrets exist
              run: |
                if [ -z "${{ secrets.RENDER_API_KEY }}" ]; then
                  echo "RENDER_API_KEY is missing!"
                  exit 1
                fi
                if [ -z "${{ secrets.RENDER_SERVICE_ID }}" ]; then
                  echo "RENDER_SERVICE_ID is missing!"
                  exit 1
                fi
                echo "All required secrets are available."
            
            - name: Trigger Render deploy (using marketplace action)
              id: render_deploy
              uses: johnbeynon/render-deploy-action@v0.0.8
              with: 
                service-id: ${{ secrets.RENDER_SERVICE_ID }}
                api-key: ${{ secrets.RENDER_API_KEY }}

            - name: Check Render deploy status
              env: 
                RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
                RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
              run: |
                echo "Fetching latest deploy for service $RENDER_SERVICE_ID..."

                DEPLOY_ID=$(curl -s \
                  -H "Authorization: Bearer $RENDER_API_KEY" \
                  "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys?limit=1" \
                  | jq -r '.[0].id')

                if [ -z "$DEPLOY_ID" ] || [ "$DEPLOY_ID" = "null" ]; then
                  echo "Could not fetch latest deploy ID"
                  exit 1
                fi

                STATUS=$(curl -s \
                  -H "Authorization: Bearer $RENDER_API_KEY" \
                  "https://api.render.com/v1/deploys/$DEPLOY_ID" \
                  | jq -r '.status')

                echo "Latest deploy ID: $DEPLOY_ID"
                echo "Status: $STATUS"

                if [ "$STATUS" = "live" ]; then
                  echo "Deploy succeeded!"
                else
                  echo "Deploy did not succeed. Status: $STATUS"
                  exit 1
                fi
